# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
    commit-message:
      prefix: ci
      include: scope
    open-pull-requests-limit: 10

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
    commit-message:
      prefix: deps
      include: scope
    open-pull-requests-limit: 10
    groups:
      laravel:
        patterns:
          - laravel/*
          - illuminate/*
      pest:
        patterns:
          - pestphp/*
      phpstan:
        patterns:
          - phpstan/*
          - larastan/*
